import {
  FaArrowUp,
  FaBars,
  FaCloud,
  FaCode,
  FaDatabase,
  FaDownload,
  FaEnvelope,
  FaExternalLinkAlt,
  FaFacebookF,
  FaGithub,
  FaGraduationCap,
  FaInstagram,
  FaLinkedinIn,
  FaMapMarkerAlt,
  FaNetworkWired,
  FaPaperPlane,
  FaPhoneAlt,
  FaReact,
  FaRocket,
  FaServer,
  FaShieldAlt,
  FaTerminal,
  FaTimes,
  FaTools,
} from 'react-icons/fa';
import { SiGmail } from 'react-icons/si';

export const Icons = {
  arrowUp: FaArrowUp,
  bars: FaBars,
  cloud: FaCloud,
  code: FaCode,
  database: FaDatabase,
  download: FaDownload,
  email: FaEnvelope,
  external: FaExternalLinkAlt,
  facebook: FaFacebookF,
  frontend: FaReact,
  github: FaGithub,
  gmail: SiGmail,
  graduation: FaGraduationCap,
  instagram: FaInstagram,
  linkedin: FaLinkedinIn,
  location: FaMapMarkerAlt,
  network: FaNetworkWired,
  paperPlane: FaPaperPlane,
  phone: FaPhoneAlt,
  rocket: FaRocket,
  backend: FaServer,
  security: FaShieldAlt,
  terminal: FaTerminal,
  times: FaTimes,
  tools: FaTools,
};
